# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: moving_period.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='moving_period.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13moving_period.proto\"\x1d\n\x0cMovingPeriod\x12\r\n\x05value\x18\x01 \x01(\x02\x62\x06proto3')
)




_MOVINGPERIOD = _descriptor.Descriptor(
  name='MovingPeriod',
  full_name='MovingPeriod',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='MovingPeriod.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=52,
)

DESCRIPTOR.message_types_by_name['MovingPeriod'] = _MOVINGPERIOD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MovingPeriod = _reflection.GeneratedProtocolMessageType('MovingPeriod', (_message.Message,), {
  'DESCRIPTOR' : _MOVINGPERIOD,
  '__module__' : 'moving_period_pb2'
  # @@protoc_insertion_point(class_scope:MovingPeriod)
  })
_sym_db.RegisterMessage(MovingPeriod)


# @@protoc_insertion_point(module_scope)
