# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: max_consecutive_loss_count.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='max_consecutive_loss_count.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n max_consecutive_loss_count.proto\"(\n\x17MaxConsecutiveLossCount\x12\r\n\x05value\x18\x01 \x01(\x05\x62\x06proto3')
)




_MAXCONSECUTIVELOSSCOUNT = _descriptor.Descriptor(
  name='MaxConsecutiveLossCount',
  full_name='MaxConsecutiveLossCount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='MaxConsecutiveLossCount.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=76,
)

DESCRIPTOR.message_types_by_name['MaxConsecutiveLossCount'] = _MAXCONSECUTIVELOSSCOUNT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MaxConsecutiveLossCount = _reflection.GeneratedProtocolMessageType('MaxConsecutiveLossCount', (_message.Message,), {
  'DESCRIPTOR' : _MAXCONSECUTIVELOSSCOUNT,
  '__module__' : 'max_consecutive_loss_count_pb2'
  # @@protoc_insertion_point(class_scope:MaxConsecutiveLossCount)
  })
_sym_db.RegisterMessage(MaxConsecutiveLossCount)


# @@protoc_insertion_point(module_scope)
