# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: testing_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import symbol_pb2 as symbol__pb2
import period_pb2 as period__pb2
import spread_pb2 as spread__pb2
import time_period_pb2 as time__period__pb2
import algorithm_pb2 as algorithm__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='testing_data.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12testing_data.proto\x1a\x0csymbol.proto\x1a\x0cperiod.proto\x1a\x0cspread.proto\x1a\x11time_period.proto\x1a\x0f\x61lgorithm.proto\"\x99\x01\n\x0bTestingData\x12\x17\n\x06symbol\x18\x01 \x01(\x0b\x32\x07.Symbol\x12\x17\n\x06period\x18\x02 \x01(\x0b\x32\x07.Period\x12\x17\n\x06spread\x18\x03 \x01(\x0b\x32\x07.Spread\x12 \n\x0btime_period\x18\x04 \x01(\x0b\x32\x0b.TimePeriod\x12\x1d\n\talgorithm\x18\x05 \x01(\x0b\x32\n.Algorithmb\x06proto3')
  ,
  dependencies=[symbol__pb2.DESCRIPTOR,period__pb2.DESCRIPTOR,spread__pb2.DESCRIPTOR,time__period__pb2.DESCRIPTOR,algorithm__pb2.DESCRIPTOR,])




_TESTINGDATA = _descriptor.Descriptor(
  name='TestingData',
  full_name='TestingData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbol', full_name='TestingData.symbol', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='period', full_name='TestingData.period', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='spread', full_name='TestingData.spread', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_period', full_name='TestingData.time_period', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='algorithm', full_name='TestingData.algorithm', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=254,
)

_TESTINGDATA.fields_by_name['symbol'].message_type = symbol__pb2._SYMBOL
_TESTINGDATA.fields_by_name['period'].message_type = period__pb2._PERIOD
_TESTINGDATA.fields_by_name['spread'].message_type = spread__pb2._SPREAD
_TESTINGDATA.fields_by_name['time_period'].message_type = time__period__pb2._TIMEPERIOD
_TESTINGDATA.fields_by_name['algorithm'].message_type = algorithm__pb2._ALGORITHM
DESCRIPTOR.message_types_by_name['TestingData'] = _TESTINGDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TestingData = _reflection.GeneratedProtocolMessageType('TestingData', (_message.Message,), {
  'DESCRIPTOR' : _TESTINGDATA,
  '__module__' : 'testing_data_pb2'
  # @@protoc_insertion_point(class_scope:TestingData)
  })
_sym_db.RegisterMessage(TestingData)


# @@protoc_insertion_point(module_scope)
