# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import data_pb2 as data__pb2
import testing_data_pb2 as testing__data__pb2
import optimization_report_pb2 as optimization__report__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rservice.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\ndata.proto\x1a\x12testing_data.proto\x1a\x19optimization_report.proto2\xd7\x03\n\x12MetaTrader4Service\x12:\n\x10get_testing_data\x12\x16.google.protobuf.Empty\x1a\x0c.TestingData\"\x00\x12:\n\x10set_testing_data\x12\x0c.TestingData\x1a\x16.google.protobuf.Empty\"\x00\x12\x33\n\x0c\x65xecute_test\x12\x0c.TestingData\x1a\x13.OptimizationReport\"\x00\x12;\n\nget_result\x12\x16.google.protobuf.Empty\x1a\x13.OptimizationReport\"\x00\x12;\n\nset_result\x12\x13.OptimizationReport\x1a\x16.google.protobuf.Empty\"\x00\x12+\n\x08get_data\x12\x05.Data\x1a\x16.google.protobuf.Empty\"\x00\x12+\n\x08set_data\x12\x16.google.protobuf.Empty\x1a\x05.Data\"\x00\x12@\n\x0c\x63heck_online\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,data__pb2.DESCRIPTOR,testing__data__pb2.DESCRIPTOR,optimization__report__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_METATRADER4SERVICE = _descriptor.ServiceDescriptor(
  name='MetaTrader4Service',
  full_name='MetaTrader4Service',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=106,
  serialized_end=577,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_testing_data',
    full_name='MetaTrader4Service.get_testing_data',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=testing__data__pb2._TESTINGDATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='set_testing_data',
    full_name='MetaTrader4Service.set_testing_data',
    index=1,
    containing_service=None,
    input_type=testing__data__pb2._TESTINGDATA,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='execute_test',
    full_name='MetaTrader4Service.execute_test',
    index=2,
    containing_service=None,
    input_type=testing__data__pb2._TESTINGDATA,
    output_type=optimization__report__pb2._OPTIMIZATIONREPORT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get_result',
    full_name='MetaTrader4Service.get_result',
    index=3,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=optimization__report__pb2._OPTIMIZATIONREPORT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='set_result',
    full_name='MetaTrader4Service.set_result',
    index=4,
    containing_service=None,
    input_type=optimization__report__pb2._OPTIMIZATIONREPORT,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get_data',
    full_name='MetaTrader4Service.get_data',
    index=5,
    containing_service=None,
    input_type=data__pb2._DATA,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='set_data',
    full_name='MetaTrader4Service.set_data',
    index=6,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=data__pb2._DATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='check_online',
    full_name='MetaTrader4Service.check_online',
    index=7,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_METATRADER4SERVICE)

DESCRIPTOR.services_by_name['MetaTrader4Service'] = _METATRADER4SERVICE

# @@protoc_insertion_point(module_scope)
