# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: servicer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import data_pb2 as data__pb2
import testing_data_pb2 as testing__data__pb2
import optimization_report_pb2 as optimization__report__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='servicer.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0eservicer.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\ndata.proto\x1a\x12testing_data.proto\x1a\x19optimization_report.proto2\xd1\x02\n\x13MetaTrader4Servicer\x12\x38\n\x0eGetTestingData\x12\x16.google.protobuf.Empty\x1a\x0c.TestingData\"\x00\x12\x38\n\x0eSetTestingData\x12\x0c.TestingData\x1a\x16.google.protobuf.Empty\"\x00\x12\x32\n\x0b\x45xecuteTest\x12\x0c.TestingData\x1a\x13.OptimizationReport\"\x00\x12:\n\tGetResult\x12\x16.google.protobuf.Empty\x1a\x13.OptimizationReport\"\x00\x12*\n\x07GetData\x12\x05.Data\x1a\x16.google.protobuf.Empty\"\x00\x12*\n\x07SetData\x12\x16.google.protobuf.Empty\x1a\x05.Data\"\x00\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,data__pb2.DESCRIPTOR,testing__data__pb2.DESCRIPTOR,optimization__report__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_METATRADER4SERVICER = _descriptor.ServiceDescriptor(
  name='MetaTrader4Servicer',
  full_name='MetaTrader4Servicer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=107,
  serialized_end=444,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetTestingData',
    full_name='MetaTrader4Servicer.GetTestingData',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=testing__data__pb2._TESTINGDATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetTestingData',
    full_name='MetaTrader4Servicer.SetTestingData',
    index=1,
    containing_service=None,
    input_type=testing__data__pb2._TESTINGDATA,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ExecuteTest',
    full_name='MetaTrader4Servicer.ExecuteTest',
    index=2,
    containing_service=None,
    input_type=testing__data__pb2._TESTINGDATA,
    output_type=optimization__report__pb2._OPTIMIZATIONREPORT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetResult',
    full_name='MetaTrader4Servicer.GetResult',
    index=3,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=optimization__report__pb2._OPTIMIZATIONREPORT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetData',
    full_name='MetaTrader4Servicer.GetData',
    index=4,
    containing_service=None,
    input_type=data__pb2._DATA,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetData',
    full_name='MetaTrader4Servicer.SetData',
    index=5,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=data__pb2._DATA,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_METATRADER4SERVICER)

DESCRIPTOR.services_by_name['MetaTrader4Servicer'] = _METATRADER4SERVICER

# @@protoc_insertion_point(module_scope)
