# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: time_period.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import date_pb2 as date__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='time_period.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11time_period.proto\x1a\ndate.proto\"D\n\nTimePeriod\x12\x1b\n\x0cinitial_date\x18\x01 \x01(\x0b\x32\x05.Date\x12\x19\n\nfinal_date\x18\x02 \x01(\x0b\x32\x05.Dateb\x06proto3')
  ,
  dependencies=[date__pb2.DESCRIPTOR,])




_TIMEPERIOD = _descriptor.Descriptor(
  name='TimePeriod',
  full_name='TimePeriod',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='initial_date', full_name='TimePeriod.initial_date', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='final_date', full_name='TimePeriod.final_date', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=101,
)

_TIMEPERIOD.fields_by_name['initial_date'].message_type = date__pb2._DATE
_TIMEPERIOD.fields_by_name['final_date'].message_type = date__pb2._DATE
DESCRIPTOR.message_types_by_name['TimePeriod'] = _TIMEPERIOD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TimePeriod = _reflection.GeneratedProtocolMessageType('TimePeriod', (_message.Message,), {
  'DESCRIPTOR' : _TIMEPERIOD,
  '__module__' : 'time_period_pb2'
  # @@protoc_insertion_point(class_scope:TimePeriod)
  })
_sym_db.RegisterMessage(TimePeriod)


# @@protoc_insertion_point(module_scope)
