# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: algorithm.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import name_pb2 as name__pb2
import algorithm_parameters_pb2 as algorithm__parameters__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='algorithm.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0f\x61lgorithm.proto\x1a\nname.proto\x1a\x1a\x61lgorithm_parameters.proto\"J\n\tAlgorithm\x12\x13\n\x04name\x18\x01 \x01(\x0b\x32\x05.Name\x12(\n\nparameters\x18\x02 \x01(\x0b\x32\x14.AlgorithmParametersb\x06proto3')
  ,
  dependencies=[name__pb2.DESCRIPTOR,algorithm__parameters__pb2.DESCRIPTOR,])




_ALGORITHM = _descriptor.Descriptor(
  name='Algorithm',
  full_name='Algorithm',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Algorithm.name', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='Algorithm.parameters', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=133,
)

_ALGORITHM.fields_by_name['name'].message_type = name__pb2._NAME
_ALGORITHM.fields_by_name['parameters'].message_type = algorithm__parameters__pb2._ALGORITHMPARAMETERS
DESCRIPTOR.message_types_by_name['Algorithm'] = _ALGORITHM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Algorithm = _reflection.GeneratedProtocolMessageType('Algorithm', (_message.Message,), {
  'DESCRIPTOR' : _ALGORITHM,
  '__module__' : 'algorithm_pb2'
  # @@protoc_insertion_point(class_scope:Algorithm)
  })
_sym_db.RegisterMessage(Algorithm)


# @@protoc_insertion_point(module_scope)
