# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: macd_sample.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import lots_pb2 as lots__pb2
import take_profit_pb2 as take__profit__pb2
import trailing_stop_pb2 as trailing__stop__pb2
import macd_open_level_pb2 as macd__open__level__pb2
import mat_trend_period_pb2 as mat__trend__period__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='macd_sample.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11macd_sample.proto\x1a\nlots.proto\x1a\x11take_profit.proto\x1a\x13trailing_stop.proto\x1a\x15macd_open_level.proto\x1a\x16mat_trend_period.proto\"\xbc\x01\n\nMACDSample\x12\x13\n\x04lots\x18\x01 \x01(\x0b\x32\x05.Lots\x12 \n\x0btake_profit\x18\x02 \x01(\x0b\x32\x0b.TakeProfit\x12$\n\rtrailing_stop\x18\x03 \x01(\x0b\x32\r.TrailingStop\x12\'\n\x0fmacd_open_level\x18\x04 \x01(\x0b\x32\x0e.MACDOpenLevel\x12(\n\x10mat_trand_period\x18\x05 \x01(\x0b\x32\x0e.MATrendPeriodb\x06proto3')
  ,
  dependencies=[lots__pb2.DESCRIPTOR,take__profit__pb2.DESCRIPTOR,trailing__stop__pb2.DESCRIPTOR,macd__open__level__pb2.DESCRIPTOR,mat__trend__period__pb2.DESCRIPTOR,])




_MACDSAMPLE = _descriptor.Descriptor(
  name='MACDSample',
  full_name='MACDSample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lots', full_name='MACDSample.lots', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='take_profit', full_name='MACDSample.take_profit', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trailing_stop', full_name='MACDSample.trailing_stop', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='macd_open_level', full_name='MACDSample.macd_open_level', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mat_trand_period', full_name='MACDSample.mat_trand_period', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=309,
)

_MACDSAMPLE.fields_by_name['lots'].message_type = lots__pb2._LOTS
_MACDSAMPLE.fields_by_name['take_profit'].message_type = take__profit__pb2._TAKEPROFIT
_MACDSAMPLE.fields_by_name['trailing_stop'].message_type = trailing__stop__pb2._TRAILINGSTOP
_MACDSAMPLE.fields_by_name['macd_open_level'].message_type = macd__open__level__pb2._MACDOPENLEVEL
_MACDSAMPLE.fields_by_name['mat_trand_period'].message_type = mat__trend__period__pb2._MATRENDPERIOD
DESCRIPTOR.message_types_by_name['MACDSample'] = _MACDSAMPLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MACDSample = _reflection.GeneratedProtocolMessageType('MACDSample', (_message.Message,), {
  'DESCRIPTOR' : _MACDSAMPLE,
  '__module__' : 'macd_sample_pb2'
  # @@protoc_insertion_point(class_scope:MACDSample)
  })
_sym_db.RegisterMessage(MACDSample)


# @@protoc_insertion_point(module_scope)
