# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: moving_average.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import lots_pb2 as lots__pb2
import maximum_risk_pb2 as maximum__risk__pb2
import decrease_factor_pb2 as decrease__factor__pb2
import moving_period_pb2 as moving__period__pb2
import moving_shift_pb2 as moving__shift__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='moving_average.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14moving_average.proto\x1a\nlots.proto\x1a\x12maximum_risk.proto\x1a\x15\x64\x65\x63rease_factor.proto\x1a\x13moving_period.proto\x1a\x12moving_shift.proto\"\xbc\x01\n\rMovingAverage\x12\x13\n\x04lots\x18\x01 \x01(\x0b\x32\x05.Lots\x12\"\n\x0cmaximum_risk\x18\x02 \x01(\x0b\x32\x0c.MaximumRisk\x12(\n\x0f\x64\x65\x63rease_factpr\x18\x03 \x01(\x0b\x32\x0f.DecreaseFactor\x12$\n\rmoving_period\x18\x04 \x01(\x0b\x32\r.MovingPeriod\x12\"\n\x0cmoving_shift\x18\x05 \x01(\x0b\x32\x0c.MovingShiftb\x06proto3')
  ,
  dependencies=[lots__pb2.DESCRIPTOR,maximum__risk__pb2.DESCRIPTOR,decrease__factor__pb2.DESCRIPTOR,moving__period__pb2.DESCRIPTOR,moving__shift__pb2.DESCRIPTOR,])




_MOVINGAVERAGE = _descriptor.Descriptor(
  name='MovingAverage',
  full_name='MovingAverage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lots', full_name='MovingAverage.lots', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='maximum_risk', full_name='MovingAverage.maximum_risk', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='decrease_factpr', full_name='MovingAverage.decrease_factpr', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='moving_period', full_name='MovingAverage.moving_period', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='moving_shift', full_name='MovingAverage.moving_shift', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=309,
)

_MOVINGAVERAGE.fields_by_name['lots'].message_type = lots__pb2._LOTS
_MOVINGAVERAGE.fields_by_name['maximum_risk'].message_type = maximum__risk__pb2._MAXIMUMRISK
_MOVINGAVERAGE.fields_by_name['decrease_factpr'].message_type = decrease__factor__pb2._DECREASEFACTOR
_MOVINGAVERAGE.fields_by_name['moving_period'].message_type = moving__period__pb2._MOVINGPERIOD
_MOVINGAVERAGE.fields_by_name['moving_shift'].message_type = moving__shift__pb2._MOVINGSHIFT
DESCRIPTOR.message_types_by_name['MovingAverage'] = _MOVINGAVERAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MovingAverage = _reflection.GeneratedProtocolMessageType('MovingAverage', (_message.Message,), {
  'DESCRIPTOR' : _MOVINGAVERAGE,
  '__module__' : 'moving_average_pb2'
  # @@protoc_insertion_point(class_scope:MovingAverage)
  })
_sym_db.RegisterMessage(MovingAverage)


# @@protoc_insertion_point(module_scope)
