// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from data.proto</summary>
public static partial class DataReflection {

  #region Descriptor
  /// <summary>File descriptor for data.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static DataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgpkYXRhLnByb3RvGhJ0ZXN0aW5nX2RhdGEucHJvdG8aGW9wdGltaXphdGlv",
          "bl9yZXBvcnQucHJvdG8iXAoERGF0YRIiCgx0ZXN0aW5nX2RhdGEYASABKAsy",
          "DC5UZXN0aW5nRGF0YRIwChNvcHRpbWl6YXRpb25fcmVwb3J0GAIgASgLMhMu",
          "T3B0aW1pemF0aW9uUmVwb3J0YgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::TestingDataReflection.Descriptor, global::OptimizationReportReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Data), global::Data.Parser, new[]{ "TestingData", "OptimizationReport" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class Data : pb::IMessage<Data> {
  private static readonly pb::MessageParser<Data> _parser = new pb::MessageParser<Data>(() => new Data());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Data> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Data() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Data(Data other) : this() {
    testingData_ = other.testingData_ != null ? other.testingData_.Clone() : null;
    optimizationReport_ = other.optimizationReport_ != null ? other.optimizationReport_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Data Clone() {
    return new Data(this);
  }

  /// <summary>Field number for the "testing_data" field.</summary>
  public const int TestingDataFieldNumber = 1;
  private global::TestingData testingData_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::TestingData TestingData {
    get { return testingData_; }
    set {
      testingData_ = value;
    }
  }

  /// <summary>Field number for the "optimization_report" field.</summary>
  public const int OptimizationReportFieldNumber = 2;
  private global::OptimizationReport optimizationReport_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::OptimizationReport OptimizationReport {
    get { return optimizationReport_; }
    set {
      optimizationReport_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Data);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Data other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(TestingData, other.TestingData)) return false;
    if (!object.Equals(OptimizationReport, other.OptimizationReport)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (testingData_ != null) hash ^= TestingData.GetHashCode();
    if (optimizationReport_ != null) hash ^= OptimizationReport.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (testingData_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(TestingData);
    }
    if (optimizationReport_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(OptimizationReport);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (testingData_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(TestingData);
    }
    if (optimizationReport_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(OptimizationReport);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Data other) {
    if (other == null) {
      return;
    }
    if (other.testingData_ != null) {
      if (testingData_ == null) {
        TestingData = new global::TestingData();
      }
      TestingData.MergeFrom(other.TestingData);
    }
    if (other.optimizationReport_ != null) {
      if (optimizationReport_ == null) {
        OptimizationReport = new global::OptimizationReport();
      }
      OptimizationReport.MergeFrom(other.OptimizationReport);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (testingData_ == null) {
            TestingData = new global::TestingData();
          }
          input.ReadMessage(TestingData);
          break;
        }
        case 18: {
          if (optimizationReport_ == null) {
            OptimizationReport = new global::OptimizationReport();
          }
          input.ReadMessage(OptimizationReport);
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
