// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from service.proto</summary>
public static partial class ServiceReflection {

  #region Descriptor
  /// <summary>File descriptor for service.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ServiceReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg1zZXJ2aWNlLnByb3RvGhtnb29nbGUvcHJvdG9idWYvZW1wdHkucHJvdG8a",
          "CmRhdGEucHJvdG8aEnRlc3RpbmdfZGF0YS5wcm90bxoZb3B0aW1pemF0aW9u",
          "X3JlcG9ydC5wcm90bzLXAgoSTWV0YVRyYWRlcjRTZXJ2aWNlEjoKEGdldF90",
          "ZXN0aW5nX2RhdGESFi5nb29nbGUucHJvdG9idWYuRW1wdHkaDC5UZXN0aW5n",
          "RGF0YSIAEjoKEHNldF90ZXN0aW5nX2RhdGESDC5UZXN0aW5nRGF0YRoWLmdv",
          "b2dsZS5wcm90b2J1Zi5FbXB0eSIAEjMKDGV4ZWN1dGVfdGVzdBIMLlRlc3Rp",
          "bmdEYXRhGhMuT3B0aW1pemF0aW9uUmVwb3J0IgASOgoJZ2V0X2VzdWx0EhYu",
          "Z29vZ2xlLnByb3RvYnVmLkVtcHR5GhMuT3B0aW1pemF0aW9uUmVwb3J0IgAS",
          "KwoIZ2V0X2RhdGESBS5EYXRhGhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5IgAS",
          "KwoIc2V0X2RhdGESFi5nb29nbGUucHJvdG9idWYuRW1wdHkaBS5EYXRhIgBi",
          "BnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::DataReflection.Descriptor, global::TestingDataReflection.Descriptor, global::OptimizationReportReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, null));
  }
  #endregion

}

#endregion Designer generated code
