// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: servicer.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from servicer.proto</summary>
public static partial class ServicerReflection {

  #region Descriptor
  /// <summary>File descriptor for servicer.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ServicerReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg5zZXJ2aWNlci5wcm90bxobZ29vZ2xlL3Byb3RvYnVmL2VtcHR5LnByb3Rv",
          "GgpkYXRhLnByb3RvGhJ0ZXN0aW5nX2RhdGEucHJvdG8aGW9wdGltaXphdGlv",
          "bl9yZXBvcnQucHJvdG8y0QIKE01ldGFUcmFkZXI0U2VydmljZXISOAoOR2V0",
          "VGVzdGluZ0RhdGESFi5nb29nbGUucHJvdG9idWYuRW1wdHkaDC5UZXN0aW5n",
          "RGF0YSIAEjgKDlNldFRlc3RpbmdEYXRhEgwuVGVzdGluZ0RhdGEaFi5nb29n",
          "bGUucHJvdG9idWYuRW1wdHkiABIyCgtFeGVjdXRlVGVzdBIMLlRlc3RpbmdE",
          "YXRhGhMuT3B0aW1pemF0aW9uUmVwb3J0IgASOgoJR2V0UmVzdWx0EhYuZ29v",
          "Z2xlLnByb3RvYnVmLkVtcHR5GhMuT3B0aW1pemF0aW9uUmVwb3J0IgASKgoH",
          "R2V0RGF0YRIFLkRhdGEaFi5nb29nbGUucHJvdG9idWYuRW1wdHkiABIqCgdT",
          "ZXREYXRhEhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GgUuRGF0YSIAYgZwcm90",
          "bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::DataReflection.Descriptor, global::TestingDataReflection.Descriptor, global::OptimizationReportReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, null));
  }
  #endregion

}

#endregion Designer generated code
